-- MySQL Script generated by MySQL Workbench
-- Sat Aug 19 12:21:12 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema RINH schedule
-- -----------------------------------------------------
-- 
-- 

-- -----------------------------------------------------
-- Schema RINH schedule
--
-- 
-- 
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `RINH schedule` DEFAULT CHARACTER SET utf8 COLLATE utf8_bin ;
USE `RINH schedule` ;

-- -----------------------------------------------------
-- Table `RINH schedule`.`Week`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RINH schedule`.`Week` (
  `idWeek` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idWeek`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RINH schedule`.`TypeLesson`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RINH schedule`.`TypeLesson` (
  `idTypeLesson` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`idTypeLesson`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RINH schedule`.`Groupe`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RINH schedule`.`Groupe` (
  `idGroupe` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idGroupe`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RINH schedule`.`Auditorium`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RINH schedule`.`Auditorium` (
  `idAuditorium` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `faculty` VARCHAR(60) NOT NULL,
  PRIMARY KEY (`idAuditorium`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RINH schedule`.`Discipline`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RINH schedule`.`Discipline` (
  `idDiscipline` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idDiscipline`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RINH schedule`.`Teacher`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RINH schedule`.`Teacher` (
  `idTeacher` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idTeacher`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RINH schedule`.`Day`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RINH schedule`.`Day` (
  `idDay` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idDay`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RINH schedule`.`Shedule`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RINH schedule`.`Shedule` (
  `id` INT NOT NULL,
  `idWeek` INT NOT NULL,
  `idDay` INT NOT NULL,
  `sequence` INT NOT NULL,
  `timeStart` TIME NOT NULL,
  `timeEnd` TIME NOT NULL,
  `idGroupe` INT NOT NULL,
  `idDiscipline` INT NOT NULL,
  `idTeacher` INT NOT NULL,
  `idTypeLesson` INT NOT NULL,
  `idAuditorium` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `Week_idx` (`idWeek` ASC) VISIBLE,
  INDEX `TypeLesson_idx` (`idTypeLesson` ASC) VISIBLE,
  INDEX `Groupe_idx` (`idGroupe` ASC) VISIBLE,
  INDEX `Auditorium_idx` (`idAuditorium` ASC) VISIBLE,
  INDEX `Discipline_idx` (`idDiscipline` ASC) VISIBLE,
  INDEX `Teacher_idx` (`idTeacher` ASC) VISIBLE,
  INDEX `Day_idx` (`idDay` ASC) VISIBLE,
  CONSTRAINT `Week`
    FOREIGN KEY (`idWeek`)
    REFERENCES `RINH schedule`.`Week` (`idWeek`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `TypeLesson`
    FOREIGN KEY (`idTypeLesson`)
    REFERENCES `RINH schedule`.`TypeLesson` (`idTypeLesson`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `Groupe`
    FOREIGN KEY (`idGroupe`)
    REFERENCES `RINH schedule`.`Groupe` (`idGroupe`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `Auditorium`
    FOREIGN KEY (`idAuditorium`)
    REFERENCES `RINH schedule`.`Auditorium` (`idAuditorium`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `Discipline`
    FOREIGN KEY (`idDiscipline`)
    REFERENCES `RINH schedule`.`Discipline` (`idDiscipline`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `Teacher`
    FOREIGN KEY (`idTeacher`)
    REFERENCES `RINH schedule`.`Teacher` (`idTeacher`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `Day`
    FOREIGN KEY (`idDay`)
    REFERENCES `RINH schedule`.`Day` (`idDay`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
